name: deploy_pro

on:
  push:
    branches: [main]

jobs:
  deploy-pro-server:
    runs-on: ubuntu-22.04

    steps:
      - name: mostrar un saludo
        run: echo "hola desde github actions con CI/CD"

      - name: mostrar directorios
        run: ls /
        
      - name: mostrar todo home  
        run: ls /home

      - name: dentro de /home/linuxbrew
        run: cd /home/linuxbrew
