name: deploy-github-pages

on: 
  push:
    branches: [main]

jobs:
  deploy-gp:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: "mensaje"
        run: echo "hola desde gp"
